CREATE TABLE IF NOT EXISTS `getApHdcrMgmRgstInfo` (
    `rnum` INT(8), 
    `platPlc` VARCHAR(200), 
    `sigunguCd` VARCHAR(5), 
    `bjdongCd` VARCHAR(5), 
    `platGbCd` CHAR(1), 
    `bun` VARCHAR(4), 
    `ji` VARCHAR(4), 
    `mgmPmsrgstPk` VARCHAR(33), 
    `bldNm` VARCHAR(100), 
    `splotNm` VARCHAR(200), 
    `block` VARCHAR(20), 
    `lot` VARCHAR(20), 
    `jimokCd` VARCHAR(2), 
    `jimokCdNm` VARCHAR(100), 
    `jiyukCd` VARCHAR(6), 
    `jiyukCdNm` VARCHAR(100), 
    `jiguCd` VARCHAR(6), 
    `jiguCdNm` VARCHAR(100), 
    `guyukCd` VARCHAR(6), 
    `guyukCdNm` VARCHAR(100), 
    `hdcrKindCd` VARCHAR(2), 
    `hdcrKindCdNm` VARCHAR(100), 
    `strctCd` CHAR(1), 
    `strctCdNm` VARCHAR(100), 
    `len` FLOAT, 
    `heit` FLOAT, 
    `area` FLOAT, 
    `bcRat` FLOAT, 
    `crtnDay` VARCHAR(8), 
	UNIQUE INDEX `bjdongCd_crtnDay_rnum_sigunguCd` (`bjdongCd`, `crtnDay`, `rnum`, `sigunguCd`)
)
COLLATE='euckr_korean_ci';