CREATE TABLE IF NOT EXISTS `getApPlatPlcInfo` (
    `rnum` INT(8), 
    `platPlc` VARCHAR(200), 
    `sigunguCd` VARCHAR(5), 
    `bjdongCd` VARCHAR(5), 
    `platGbCd` CHAR(1), 
    `bun` VARCHAR(4), 
    `ji` VARCHAR(4), 
    `mgmPlatPlcPk` VARCHAR(33), 
    `mgmPmsrgstPk` VARCHAR(33), 
    `mgmDongOulnPk` VARCHAR(33), 
    `reprYn` VARCHAR(1), 
    `mainDongGbCd` VARCHAR(1), 
    `mainDongGbCdNm` VARCHAR(100), 
    `hjdongCd` VARCHAR(3), 
    `splotNm` VARCHAR(200), 
    `block` VARCHAR(20), 
    `lot` VARCHAR(20), 
    `jimokCd` VARCHAR(2), 
    `jimokCdNm` VARCHAR(100), 
    `relJibunNm` VARCHAR(100), 
    `crtnDay` VARCHAR(8), 
	UNIQUE INDEX `bjdongCd_crtnDay_rnum_sigunguCd` (`bjdongCd`, `crtnDay`, `rnum`, `sigunguCd`)
)
COLLATE='euckr_korean_ci';