CREATE TABLE IF NOT EXISTS `getApDemolExtngMgmRgstInfo` (
    `rnum` INT(8), 
    `platPlc` VARCHAR(200), 
    `sigunguCd` VARCHAR(5), 
    `bjdongCd` VARCHAR(5), 
    `platGbCd` CHAR(1), 
    `bun` VARCHAR(4), 
    `ji` VARCHAR(4), 
    `mgmPmsrgstPk` VARCHAR(33), 
    `bldNm` VARCHAR(100), 
    `splotNm` VARCHAR(200), 
    `block` VARCHAR(20), 
    `lot` VARCHAR(20), 
    `demolExtngGbCd` CHAR(1), 
    `demolExtngGbCdNm` VARCHAR(100), 
    `demolStrtDay` VARCHAR(8), 
    `demolEndDay` VARCHAR(8), 
    `demolExtngDay` VARCHAR(8), 
    `totArea` FLOAT, 
    `bldCnt` INT(5), 
    `mainPurpsCd` VARCHAR(5), 
    `mainPurpsCdNm` VARCHAR(100), 
    `strctCd` CHAR(1), 
    `strctCdNm` VARCHAR(100), 
    `hhldCnt` FLOAT, 
    `hoCnt` FLOAT, 
    `fmlyCnt` FLOAT, 
    `cemaIncYn` VARCHAR(1), 
    `himaIncYn` VARCHAR(1), 
    `rfmaIncYn` VARCHAR(1), 
    `lgmaIncYn` VARCHAR(1), 
    `etcIncYn` VARCHAR(1), 
    `nabYn` VARCHAR(1), 
    `etcYn` VARCHAR(1), 
    `btmaIncYn` VARCHAR(1), 
    `crtnDay` VARCHAR(8), 
	UNIQUE INDEX `bjdongCd_crtnDay_rnum_sigunguCd` (`bjdongCd`, `crtnDay`, `rnum`, `sigunguCd`)
)
COLLATE='euckr_korean_ci';