CREATE TABLE IF NOT EXISTS `getApTmpBldInfo` (
    `rnum` INT(8), 
    `platPlc` VARCHAR(200), 
    `sigunguCd` VARCHAR(5), 
    `bjdongCd` VARCHAR(5), 
    `platGbCd` CHAR(1), 
    `bun` VARCHAR(4), 
    `ji` VARCHAR(4), 
    `mgmPmsrgstPk` VARCHAR(33), 
    `bldNm` VARCHAR(100), 
    `splotNm` VARCHAR(200), 
    `block` VARCHAR(20), 
    `lot` VARCHAR(20), 
    `sumArchArea` FLOAT, 
    `sumTotArea` FLOAT, 
    `platArea` FLOAT, 
    `tmpbldPrsvExpDay` VARCHAR(8), 
    `strctCd` CHAR(1), 
    `strctCdNm` VARCHAR(100), 
    `mainPurpsCd` VARCHAR(5), 
    `mainPurpsCdNm` VARCHAR(100), 
    `archArea` FLOAT, 
    `totArea` FLOAT, 
    `grndFlrCnt` INT(5), 
    `crtnDay` VARCHAR(8), 
	UNIQUE INDEX `bjdongCd_crtnDay_rnum_sigunguCd` (`bjdongCd`, `crtnDay`, `rnum`, `sigunguCd`)
)
COLLATE='euckr_korean_ci';