CREATE TABLE IF NOT EXISTS `getApDongOulnInfo` (
    `rnum` INT(8), 
    `platPlc` VARCHAR(200), 
    `sigunguCd` VARCHAR(5), 
    `bjdongCd` VARCHAR(5), 
    `platGbCd` CHAR(1), 
    `bun` VARCHAR(4), 
    `ji` VARCHAR(4), 
    `mgmDongOulnPk` VARCHAR(33), 
    `mgmPmsrgstPk` VARCHAR(33), 
    `bldNm` VARCHAR(100), 
    `splotNm` VARCHAR(200), 
    `block` VARCHAR(20), 
    `lot` VARCHAR(20), 
    `mainAtchGbCd` CHAR(1), 
    `mainAtchGbCdNm` VARCHAR(100), 
    `mainPurpsCd` VARCHAR(5), 
    `mainPurpsCdNm` VARCHAR(100), 
    `hoCnt` INT(5), 
    `fmlyCnt` INT(5), 
    `hhldCnt` INT(5), 
    `strctCd` CHAR(1), 
    `strctCdNm` VARCHAR(100), 
    `roofCd` VARCHAR(2), 
    `roofCdNm` VARCHAR(100), 
    `archArea` FLOAT, 
    `totArea` FLOAT, 
    `vlRatEstmTotArea` FLOAT, 
    `crtnDay` VARCHAR(8), 
	UNIQUE INDEX `bjdongCd_crtnDay_rnum_sigunguCd` (`bjdongCd`, `crtnDay`, `rnum`, `sigunguCd`)
)
COLLATE=`euckr_korean_ci`;