CREATE TABLE IF NOT EXISTS `getApBasisOulnInfo` (
    `rnum` INT(8), 
    `platPlc` VARCHAR(200), 
    `sigunguCd` VARCHAR(5), 
    `bjdongCd` VARCHAR(5), 
    `platGbCd` CHAR(1), 
    `bun` VARCHAR(4), 
    `ji` VARCHAR(4), 
    `mgmPmsrgstPk` VARCHAR(33), 
    `bldNm` VARCHAR(100), 
    `splotNm` VARCHAR(200), 
    `block` VARCHAR(20), 
    `lot` VARCHAR(20), 
    `jimokCdNm` VARCHAR(100), 
    `jiyukCdNm` VARCHAR(100), 
    `jiguCdNm` VARCHAR(100), 
    `guyukCdNm` VARCHAR(100), 
    `jimokCd` VARCHAR(2), 
    `jiyukCd` VARCHAR(6), 
    `jiguCd` VARCHAR(6), 
    `guyukCd` VARCHAR(6), 
    `archGbCdNm` VARCHAR(4), 
    `archGbCd` VARCHAR(100), 
    `platArea` FLOAT, 
    `archArea` FLOAT, 
    `bcRat` FLOAT, 
    `totArea` FLOAT, 
    `vlRatEstmTotArea` FLOAT, 
    `vlRat` FLOAT, 
    `mainBldCnt` INT(5), 
    `atchBldDongCnt` INT(5), 
    `mainPurpsCd` VARCHAR(5), 
    `mainPurpsCdNm` VARCHAR(100), 
    `hhldCnt` INT(5), 
    `hoCnt` INT(5), 
    `fmlyCnt` INT(5), 
    `totPkngCnt` INT(7), 
    `stcnsSchedDay` VARCHAR(8), 
    `stcnsDelayDay` VARCHAR(8), 
    `realStcnsDay` VARCHAR(8), 
    `archPmsDay` VARCHAR(8), 
    `useAprDay` VARCHAR(8), 
    `crtnDay` VARCHAR(8), 
	UNIQUE INDEX `bjdongCd_crtnDay_rnum_sigunguCd` (`bjdongCd`, `crtnDay`, `rnum`, `sigunguCd`)
)
COLLATE=`euckr_korean_ci`;