CREATE TABLE IF NOT EXISTS `getApExposPubuseAreaInfo` (
    `rnum` INT(8), 
    `platPlc` VARCHAR(200), 
    `sigunguCd` VARCHAR(5), 
    `bjdongCd` VARCHAR(5), 
    `platGbCd` CHAR(1), 
    `bun` VARCHAR(4), 
    `ji` VARCHAR(4), 
    `mgmExposPubuseAreaPk` VARCHAR(33), 
    `mgmPmsrgstPk` VARCHAR(33), 
    `splotNm` VARCHAR(200), 
    `block` VARCHAR(20), 
    `lot` VARCHAR(20), 
    `pngtypGbNm` VARCHAR(100), 
    `exposPubuseGbCd` CHAR(1), 
    `exposPubuseGbCdNm` VARCHAR(100), 
    `mainAtchGbCd` CHAR(1), 
    `mainAtchGbCdNm` VARCHAR(100), 
    `flrGbCd` VARCHAR(2), 
    `flrGbCdNm` VARCHAR(100), 
    `flrNo` INT(4), 
    `strctCd` CHAR(1), 
    `strctCdNm` VARCHAR(100), 
    `mainPurpsCd` VARCHAR(5), 
    `mainPurpsCdNm` VARCHAR(100), 
    `etcPurps` VARCHAR(500), 
    `area` FLOAT, 
    `crtnDay` VARCHAR(8), 
	UNIQUE INDEX `bjdongCd_crtnDay_rnum_sigunguCd` (`bjdongCd`, `crtnDay`, `rnum`, `sigunguCd`)
)
COLLATE='euckr_korean_ci';